#!/bin/bash
# Script Auto Installer VPS by Gidhan Bagus Algary
# Initialisasi Var
OS=`uname -p`;

# data pemilik server
read -p "Masukkan username untuk akun default: " dname
read -p "Maks login user (contoh 1 atau 2): " llimit
echo "Proses instalasi script dimulai....."

# update software server
yum update -y

# go to root
cd

# disable se linux
echo 0 > /selinux/enforce
sed -i 's/SELINUX=enforcing/SELINUX=disable/g' /etc/sysconfig/selinux

# set locale
sed -i 's/AcceptEnv/#AcceptEnv/g' /etc/ssh/sshd_config
service sshd restart

# disable ipv6
echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6
sed -i '$ i\echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6' /etc/rc.local
sed -i '$ i\echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6' /etc/rc.d/rc.local

# set time GMT +7
ln -fs /usr/share/zoneinfo/Asia/Jakarta /etc/localtime

# install wget and curl
yum -y install wget curl

# banner ssh
wget -O /etc/pesan "https://raw.githubusercontent.com/gidhanbagus/scriptasu/master/conf/pesan"
echo "Banner /etc/pesan" >> /etc/ssh/sshd_config

# setting repo
wget http://dl.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm
wget http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
rpm -Uvh epel-release-6-8.noarch.rpm
rpm -Uvh remi-release-6.rpm

if [ "$OS" == "x86_64" ]; then
  wget https://raw.githubusercontent.com/gidhanbagus/scriptasu/master/app/rpmforge.rpm
  rpm -Uvh rpmforge.rpm
else
  wget https://raw.githubusercontent.com/gidhanbagus/scriptasu/master/app/rpmforge.rpm
  rpm -Uvh rpmforge.rpm
fi

sed -i 's/enabled = 1/enabled = 0/g' /etc/yum.repos.d/rpmforge.repo
sed -i -e "/^\[remi\]/,/^\[.*\]/ s|^\(enabled[ \t]*=[ \t]*0\\)|enabled=1|" /etc/yum.repos.d/remi.repo
rm -f *.rpm

# remove unused
yum -y remove sendmail;
yum -y remove httpd;
yum -y remove cyrus-sasl

# update
yum -y update

# install webserver
yum -y install nginx php-fpm php-cli
service nginx start
service php-fpm start
chkconfig nginx on
chkconfig php-fpm on

# install essential package
yum -y install rrdtool screen iftop htop nmap bc nethogs openvpn vnstat ngrep mtr git zsh mrtg unrar rsyslog rkhunter mrtg net-snmp net-snmp-utils expect nano bind-utils
yum -y groupinstall 'Development Tools'
yum -y install cmake
yum -y --enablerepo=rpmforge install axel sslh ptunnel unrar

# disable exim
service exim stop
chkconfig exim off

# setting vnstat
vnstat -u -i eth0
echo "MAILTO=root" > /etc/cron.d/vnstat
echo "*/5 * * * * root /usr/sbin/vnstat.cron" >> /etc/cron.d/vnstat
service vnstat restart
chkconfig vnstat on

# install screenfetch
cd
wget https://raw.githubusercontent.com/gidhanbagus/scriptasu/master/app/screenfetch-dev
mv screenfetch-dev /usr/bin/screenfetch
chmod +x /usr/bin/screenfetch
echo "clear" >> .bash_profile
echo "screenfetch" >> .bash_profile

# setting webserver
cd
wget -O /etc/nginx/nginx.conf "https://raw.githubusercontent.com/gidhanbagus/scriptasu/master/conf/nginx.conf"
sed -i 's/www-data/nginx/g' /etc/nginx/nginx.conf
mkdir -p /home/vps/public_html
echo "<pre>Setup by Gidhan Bagus Algary</pre>" > /home/vps/public_html/index.html
echo "<?php phpinfo(); ?>" > /home/vps/public_html/info.php
rm /etc/nginx/conf.d/*
wget -O /etc/nginx/conf.d/vps.conf "https://raw.githubusercontent.com/gidhanbagus/scriptasu/master/conf/vps.conf"
sed -i 's/apache/nginx/g' /etc/php-fpm.d/www.conf
chmod -R +rx /home/vps
service php-fpm restart
service nginx restart

# install openvpn
wget -O /etc/openvpn/openvpn.zip "https://raw.githubusercontent.com/gidhanbagus/scriptasu/master/conf/openvpn-key.zip"
cd /etc/openvpn/
unzip openvpn.zip
wget -O /etc/openvpn/80.conf "https://raw.githubusercontent.com/gidhanbagus/scriptasu/master/conf/80-centos.conf"
if [ "$OS" == "x86_64" ]; then
  wget -O /etc/openvpn/80.conf "https://raw.githubusercontent.com/gidhanbagus/scriptasu/master/conf/80-centos64.conf"
fi
wget -O /etc/iptables.up.rules "https://raw.githubusercontent.com/gidhanbagus/scriptasu/master/conf/iptables.up.rules"
sed -i '$ i\iptables-restore < /etc/iptables.up.rules' /etc/rc.local
sed -i '$ i\iptables-restore < /etc/iptables.up.rules' /etc/rc.d/rc.local
MYIP=`curl icanhazip.com`;
MYIP2="s/xxxxxxxxx/$MYIP/g";
sed -i $MYIP2 /etc/iptables.up.rules;
sed -i 's/venet0/eth0/g' /etc/iptables.up.rules
iptables-restore < /etc/iptables.up.rules
sysctl -w net.ipv4.ip_forward=1
sed -i 's/net.ipv4.ip_forward = 0/net.ipv4.ip_forward = 1/g' /etc/sysctl.conf
service openvpn restart
chkconfig openvpn on
cd

# configure openvpn client config
cd /etc/openvpn/
wget -O /etc/openvpn/client.ovpn "https://raw.githubusercontent.com/gidhanbagus/scriptasu/master/openvpn.conf"
sed -i $MYIP2 /etc/openvpn/client.ovpn;
useradd -g 0 -d /root/ -s /bin/bash $dname
echo $dname:"sarkem123" | chpasswd
echo $dname > pass.txt
echo "sarkem123" >> pass.txt
tar cf client.tar client.ovpn pass.txt
cp client.tar /home/vps/public_html/
cp client.ovpn /home/vps/public_html/

# install badvpn
cd
wget -O /usr/bin/badvpn-udpgw "https://raw.githubusercontent.com/gidhanbagus/scriptasu/master/conf/badvpn-udpgw"
if [ "$OS" == "x86_64" ]; then
  wget -O /usr/bin/badvpn-udpgw "https://raw.githubusercontent.com/gidhanbagus/scriptasu/master/conf/badvpn-udpgw64"
fi
sed -i '$ i\screen -AmdS badvpn badvpn-udpgw --listen-addr 127.0.0.1:7300' /etc/rc.local
sed -i '$ i\screen -AmdS badvpn badvpn-udpgw --listen-addr 127.0.0.1:7300' /etc/rc.d/rc.local
chmod +x /usr/bin/badvpn-udpgw
screen -AmdS badvpn badvpn-udpgw --listen-addr 127.0.0.1:7300

# install mrtg
cd /etc/snmp/
wget -O /etc/snmp/snmpd.conf "https://raw.githubusercontent.com/gidhanbagus/scriptasu/master/conf/snmpd.conf"
wget -O /root/mrtg-mem.sh "https://raw.githubusercontent.com/gidhanbagus/scriptasu/master/conf/mrtg-mem.sh"
chmod +x /root/mrtg-mem.sh
service snmpd restart
chkconfig snmpd on
snmpwalk -v 1 -c public localhost | tail
mkdir -p /home/vps/public_html/mrtg
cfgmaker --zero-speed 100000000 --global 'WorkDir: /home/vps/public_html/mrtg' --output /etc/mrtg/mrtg.cfg public@localhost
curl "https://raw.githubusercontent.com/gidhanbagus/scriptasu/master/conf/mrtg.conf" >> /etc/mrtg/mrtg.cfg
sed -i 's/WorkDir: \/var\/www\/mrtg/# WorkDir: \/var\/www\/mrtg/g' /etc/mrtg/mrtg.cfg
sed -i 's/# Options\[_\]: growright, bits/Options\[_\]: growright/g' /etc/mrtg/mrtg.cfg
indexmaker --output=/home/vps/public_html/mrtg/index.html /etc/mrtg/mrtg.cfg
echo "0-59/5 * * * * root env LANG=C /usr/bin/mrtg /etc/mrtg/mrtg.cfg" > /etc/cron.d/mrtg
LANG=C /usr/bin/mrtg /etc/mrtg/mrtg.cfg
LANG=C /usr/bin/mrtg /etc/mrtg/mrtg.cfg
LANG=C /usr/bin/mrtg /etc/mrtg/mrtg.cfg

# setting port ssh
cd
sed -i '/Port 22/a Port 143' /etc/ssh/sshd_config
sed -i 's/#Port 22/Port  22/g' /etc/ssh/sshd_config
service sshd restart
chkconfig sshd on

# install dropbear
yum -y install dropbear
echo "OPTIONS=\"-p 109 -p 110 -p 443 -b /etc/pesan\"" > /etc/sysconfig/dropbear
echo "/bin/false" >> /etc/shells
echo "PIDFILE=/var/run/dropbear.pid" >> /etc/init.d/dropbear
service dropbear restart
chkconfig dropbear on

# install vnstat gui
cd /home/vps/public_html/
wget https://raw.githubusercontent.com/gidhanbagus/scriptasu/master/app/vnstat_php_frontend-1.5.1.tar.gz
tar xf vnstat_php_frontend-1.5.1.tar.gz
rm vnstat_php_frontend-1.5.1.tar.gz
mv vnstat_php_frontend-1.5.1 vnstat
cd vnstat
sed -i "s/\$iface_list = array('eth0', 'sixxs');/\$iface_list = array('eth0');/g" config.php
sed -i "s/\$language = 'nl';/\$language = 'en';/g" config.php
sed -i 's/Internal/Internet/g' config.php
sed -i '/SixXS IPv6/d' config.php

# install fail2ban
cd
yum -y install fail2ban
service fail2ban start
chkconfig fail2ban on

# install squid
wget https://raw.githubusercontent.com/gidhanbagus/scriptasu/master/squid.sh
chmod 100 squid.sh
./squid.sh

# install webmin
cd
wget http://prdownloads.sourceforge.net/webadmin/webmin-1.831-1.noarch.rpm
yum -y install perl perl-Net-SSLeay openssl perl-IO-Tty
rpm -U webmin*
rm -f webmin*
sed -i -e 's/ssl=1/ssl=0/g' /etc/webmin/miniserv.conf
service webmin restart
chkconfig webmin on

# pasang bmon
if [ "$OS" == "x86_64" ]; then
  wget -O /usr/bin/bmon "https://raw.githubusercontent.com/gidhanbagus/scriptasu/master/conf/bmon64"
else
  wget -O /usr/bin/bmon "https://raw.githubusercontent.com/gidhanbagus/scriptasu/master/conf/bmon"
fi
chmod +x /usr/bin/bmon

# auto kill multi login
echo "while :" >> /usr/bin/autokill
echo "  do" >> /usr/bin/autokill
echo "  userlimit $llimit" >> /usr/bin/autokill
echo "  sleep 5" >> /usr/bin/autokill
echo "  done" >> /usr/bin/autokill


# download script
cd
wget -O /usr/bin/user-trial "https://raw.githubusercontent.com/cobrasta25/zhangzi/master/user-trial"
wget -O /usr/bin/rubah-tanggal "https://raw.githubusercontent.com/cobrasta25/zhangzi/master/rubah-tanggal"
wget -O /usr/bin/next "https://raw.githubusercontent.com/cobrasta25/zhangzi/master/next"
wget -O /usr/bin/auto-reboot "https://raw.githubusercontent.com/cobrasta25/zhangzi/master/auto-reboot"
wget -O /usr/bin/bench-network "https://raw.githubusercontent.com/cobrasta25/zhangzi/master/bench-network"
wget -O /usr/bin/speedtest "https://raw.githubusercontent.com/cobrasta25/zhangzi/master/speedtest"
wget -O /usr/bin/ps-mem "https://raw.githubusercontent.com/cobrasta25/zhangzi/master/ps-mem"
wget -O /usr/bin/autokill "https://raw.githubusercontent.com/cobrasta25/zhangzi/master/autokill"
wget -O /usr/bin/dropmon "https://raw.githubusercontent.com/cobrasta25/zhangzi/master/dropmon"
wget -O /usr/bin/menu "https://raw.githubusercontent.com/cobrasta25/zhangzi/master/menu"
wget -O /usr/bin/user-active-list "https://raw.githubusercontent.com/cobrasta25/zhangzi/master/user-active-list"
wget -O /usr/bin/user-add "https://raw.githubusercontent.com/cobrasta25/zhangzi/master/user-add"
wget -O /usr/bin/user-add-pptp "https://raw.githubusercontent.com/cobrasta25/zhangzi/master/user-add-pptp"
wget -O /usr/bin/user-del "https://raw.githubusercontent.com/cobrasta25/zhangzi/master/user-del"
wget -O /usr/bin/disable-user-expire "https://raw.githubusercontent.com/cobrasta25/zhangzi/master/disable-user-expire"
wget -O /usr/bin/delete-user-expire "https://raw.githubusercontent.com/cobrasta25/zhangzi/master/delete-user-expire"
wget -O /usr/bin/banned-user "https://raw.githubusercontent.com/cobrasta25/zhangzi/master/banned-user"
wget -O /usr/bin/unbanned-user "https://raw.githubusercontent.com/cobrasta25/zhangzi/master/unbanned-user"
wget -O /usr/bin/user-expire-list "https://raw.githubusercontent.com/cobrasta25/zhangzi/master/user-expire-list"
wget -O /usr/bin/user-gen "https://raw.githubusercontent.com/cobrasta25/zhangzi/master/user-gen"
wget -O /usr/bin/userlimit.sh "https://raw.githubusercontent.com/cobrasta25/zhangzi/master/userlimit.sh"
#wget -O /usr/bin/userlimitssh.sh "https://raw.githubusercontent.com/cobrasta25/zhangzi/master/userlimitssh.sh"
wget -O /usr/bin/user-list "https://raw.githubusercontent.com/cobrasta25/zhangzi/master/user-list"
wget -O /usr/bin/user-login "https://raw.githubusercontent.com/cobrasta25/zhangzi/master/user-login"
wget -O /usr/bin/user-pass "https://raw.githubusercontent.com/cobrasta25/zhangzi/master/user-pass"
wget -O /usr/bin/user-renew "https://raw.githubusercontent.com/cobrasta25/zhangzi/master/user-renew"
wget -O /usr/bin/clearcache.sh "https://raw.githubusercontent.com/cobrasta25/zhangzi/master/clearcache.sh"
wget -O /usr/bin/bannermenu "https://raw.githubusercontent.com/cobrasta25/zhangzi/master/bannermenu"
wget -O /usr/bin/menu-update-script-vps.sh "https://raw.githubusercontent.com/cobrasta25/zhangzi/master/menu-update-script-vps.sh"
cd
# cronjob
echo "*/30 * * * * root service dropbear restart" > /etc/cron.d/dropbear
echo "00 23 * * * root /usr/bin/disable-user-expire" > /etc/cron.d/disable-user-expire
echo "0 */12 * * * root /sbin/reboot" > /etc/cron.d/reboot
echo "00 01 * * * root echo 3 > /proc/sys/vm/drop_caches && swapoff -a && swapon -a" > /etc/cron.d/clearcacheram3swap
echo "*/3 * * * * root /usr/bin/clearcache.sh" > /etc/cron.d/clearcache1

cd
chmod +x /usr/bin/user-trial
chmod +x /usr/bin/rubah-tanggal
chmod +x /usr/bin/rubah-port
chmod +x /usr/bin/next
chmod +x /usr/bin/auto-reboot
chmod +x /usr/bin/bench-network
chmod +x /usr/bin/speedtest
chmod +x /usr/bin/ps-mem
#chmod +x /usr/bin/autokill
chmod +x /usr/bin/dropmon
chmod +x /usr/bin/menu
chmod +x /usr/bin/user-active-list
chmod +x /usr/bin/user-add
chmod +x /usr/bin/user-add-pptp
chmod +x /usr/bin/user-del
chmod +x /usr/bin/disable-user-expire
chmod +x /usr/bin/delete-user-expire
chmod +x /usr/bin/banned-user
chmod +x /usr/bin/unbanned-user
chmod +x /usr/bin/user-expire-list
chmod +x /usr/bin/user-gen
chmod +x /usr/bin/userlimit.sh
chmod +x /usr/bin/userlimitssh.sh
chmod +x /usr/bin/user-list
chmod +x /usr/bin/user-login
chmod +x /usr/bin/user-pass
chmod +x /usr/bin/user-renew
chmod +x /usr/bin/clearcache.sh
chmod +x /usr/bin/bannermenu
chmod +x /usr/bin/menu-update-script-vps.sh
cd


# cron
cd
service crond start
chkconfig crond on
service crond stop
echo "0 0 * * * root /usr/bin/gusur" > /etc/cron.d/gusur
echo "0 0 * * * root /root/reboot.sh" > /etc/cron.d/reboot_otomatis
echo "* * * * * root /usr/bin/cron-autokill" > /etc/cron.d/autokill
echo "* * * * * root /usr/bin/cron-dropcheck" > /etc/cron.d/dropcheck

# finalisasi
chown -R nginx:nginx /home/vps/public_html
service nginx start
service php-fpm start
service vnstat restart
service openvpn restart
service snmpd restart
service sshd restart
service dropbear restart
service fail2ban restart
service squid restart
service webmin restart
service crond start
chkconfig crond on

# info
echo "Layanan yang diaktifkan"  | tee -a log-install.txt
echo "--------------------------------------"  | tee -a log-install.txt
echo "OpenVPN : TCP 80 (client config : http://$MYIP:81/client.ovpn)"  | tee -a log-install.txt
echo "Port OpenSSH : 22, 143"  | tee -a log-install.txt
echo "Port Dropbear : 109, 110, 443"  | tee -a log-install.txt
echo "SquidProxy    : 8080, 3128 (Limit to IP SSH)"  | tee -a log-install.txt
echo "Badvpn   : badvpn-udpgw port 7300"  | tee -a log-install.txt
echo "Webmin   : http://$MYIP:10000/"  | tee -a log-install.txt
echo "Vnstat   : http://$MYIP:81/vnstat/"  | tee -a log-install.txt
echo "MRTG     : http://$MYIP:81/mrtg/"  | tee -a log-install.txt
echo "Timezone : Asia/Jakarta"  | tee -a log-install.txt
echo "Fail2Ban : [on]"  | tee -a log-install.txt
echo "IPv6     : [off]"  | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo "Tools"  | tee -a log-install.txt
echo "-----"  | tee -a log-install.txt
echo "axel, bmon, htop, iftop, mtr, nethogs"  | tee -a log-install.txt
echo "" | tee -a log-install.txt
echo "Account Default (untuk SSH dan VPN)"  | tee -a log-install.txt
echo "---------------"  | tee -a log-install.txt
echo "User     : $dname"  | tee -a log-install.txt
echo "Password : sarkem123"  | tee -a log-install.txt
echo "" | tee -a log-install.txt
echo "Script Command"  | tee -a log-install.txt
echo "--------------"  | tee -a log-install.txt
echo "speedtest --share : untuk cek speed vps"  | tee -a log-install.txt
echo "ram : untuk melihat pemakaian ram"  | tee -a log-install.txt
echo "buat : untuk membuat akun baru"  | tee -a log-install.txt
echo "akun : untuk melihat daftar akun beserta masa aktifnya"  | tee -a log-install.txt
echo "userlimit <limit> : untuk kill akun yang login lebih dari <limit>. Cth: userlimit 1"  | tee -a log-install.txt
echo "cek  : untuk melihat user yang sedang login"  | tee -a log-install.txt
echo "hapus  : untuk menghapus user"  | tee -a log-install.txt
echo "gusur  : untuk menggusur akun yang sudah expired"  | tee -a log-install.txt
echo "trial : untuk membuat akun trial selama 1 hari"  | tee -a log-install.txt
echo "info : untuk melihat ulang informasi ini"  | tee -a log-install.txt
echo "logreboot : untuk melihat log reboot vps"  | tee -a log-install.txt
echo "--------------"  | tee -a log-install.txt
rm -f /root/zzz
